### ISSUE TITLE
Feature Request: Supporting Horizontal values

### ISSUE THREAD

**Issue by jooyoungseo** [mltony/nvda-audio-chart#1]
Before everything else, thank you very much for developing such a wonderful add-on for NVDA users.

I was wondering if you could consider the following request for the future enhancement.

Currently, AudioChart only supports a numeric variable presented in a vertical manner. I understand that many data frames are in a long format like one-variable-per-column type.

However, we sometimes come across a wide format data frame where each variable is presented horizontally with row headers being variable names.

Could you please by chance improve the add-on to support selected numeric values in a horizontal row?

That would be so much appreciated.

**Comment by mltony** [comment]
If your time series is presented in a row, you can select this row and 
press the same NVDA-A command. Would this work for your scenario?

**Comment by jooyoungseo** [comment]
Aw, that works @mltonycommented.

I am sorry for not double-checking it before filing this issue.

Thank you very much and I will close this issue.
